import Foundation

enum AuthorizedKeys {
    // Generated by Scripts/make-keys.sh; replace with the actual 32-byte public key (hex).
    // The matching private key MUST live offline (1Password / encrypted external disk),
    // never in this repo.
    static let publicKeyHex = "dee770a32eb5c6c4807347cd8d47c695a84b8f95e2c02986e8788e0f6911c49f"

    static var publicKeyData: Data {
        Data(hex: publicKeyHex)
    }
}

private extension Data {
    init(hex: String) {
        var data = Data(capacity: hex.count / 2)
        var byte: UInt8 = 0
        for (i, char) in hex.enumerated() {
            guard let nibble = char.hexDigitValue else { continue }
            if i % 2 == 0 {
                byte = UInt8(nibble) << 4
            } else {
                byte |= UInt8(nibble)
                data.append(byte)
            }
        }
        self = data
    }
}
